pipeline {
    agent any 
    tools {maven 'maven'}
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
                sh 'mvn clean package -f demo/pom.xml '
            }
        }
        stage('SonarQube Analysis') {
        steps{
            withSonarQubeEnv() {
            sh "mvn clean verify sonar:sonar -Dsonar.projectKey=qualitycheck -Dsonar.projectName='qualitycheck'"
          }
       }
        }
         stage('Build docker image'){
            steps{
                dir('demo'){
                script{
                    sh 'docker build -t assignment .'
                }
            }
        }
    }
        stage('Deploy') {
            steps {
                sh 'docker run -d -p 8090:8090 assignment'
            }
        }
}
}
