pipeline {
    agent any 
    tools {maven 'maven'}
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
                sh 'mvn clean package -f demo/pom.xml '
            }
        }
        stage('Quality Chcek'){
            steps{
                withSonarQubeEnv(credentialsId: 'sonarqube-token', installationName:'SonarQube') {
                    sh '''mvn clean verify sonar:sonar -Dsonar.projectKey=assignment3pipeline -Dsonar.projectName='assignment3pipeline' -Dsonar.host.url=
http://localhost:9000'''
               }
            }            
        }
         stage('Build docker image'){
            steps{
                dir('demo'){
                script{
                    sh 'docker build -t assignment .'
                }
            }
        }
    }
        stage('Deploy') {
            steps {
                sh 'docker run -d -p 8090:8090 assignment'
            }
        }
}
}
